### ISSUE TITLE
Remove dependency on IPv6

### ISSUE THREAD

**Issue by L3P3** [Parakoopa/riptide-engine-docker#1]
When I started riptide today, I got the following error:
```
ERROR starting container. : APIError(500 Server Error for http+docker://localhost/v1.41/containers/d5e8e5e1a0bb21668ade5baf96385915720605a5aa90b77d28ed885cb6aa6aa3/start: Internal Server Error ("driver failed programming external connectivity on endpoint riptide__projekt__www (dff5e91a5c84354eb390869887d2e0736bc364252fc1a098cb4ca5d95f850a80): Error starting userland proxy: listen tcp6 [::]:30000: socket: address family not supported by protocol"))
```

For several reasons, IPv6 is disabled in my used kernel. Starting that service worked just a few days ago.
It appears that somewhere, docker is configured to use IPv6 now which does not make any sense in this application. Please revert that behaviour if possible, enabling IPv6 in my kernel is not an acceptable long-term option.

I hope this is the proper project for that. :grin:

**Comment by Parakoopa** [comment]
Hi, this is a Docker related issue, please see the documentation of Docker on how to disable this, there's sadly not much I can do on the Riptide side of things.
